export const constants = {
	testIds: {
		generalNavTabPane: 'general-nav-tab-pane',
		mockId: 'mock-id',
		mockName: 'mock-name',
		description: 'mock-description',
		entityStatus: 'mock-entity-status',
		httpMethod: 'mock-http-method',
		route: 'mock-route',
		queryParams: 'mock-query-params',
		statusCode: 'mock-status-code',
		createdBy: 'mock-created-by',
		createdAt: 'mock-created-at',
		lastModifiedBy: 'mock-last-modified-by',
		lastModifiedAt: 'mock-last-modified-at',
	},
	labels: {
		mockId: 'Mock Unique Identifier',
		mockName: 'Mock Name',
		description: 'Description',
		entityStatus: 'Status',
		httpMethod: 'HTTP Method',
		route: 'Route',
		queryParams: 'Query Params',
		statusCode: 'Expected Status Code',
		createdBy: 'Created By',
		createdAt: 'Created At',
		lastModifiedBy: 'Last Modified By',
		lastModifiedAt: 'Last Modified At',
	},
	defaultFieldType: 'text',
};
