# These configurations are purely for development purposes.
# It is not be used in the production environment.
logging:
  level:
    root: INFO

server:
  error:
    whitelabel:
      enabled: false
  ssl:
    enabled: false
    key-store: src/main/resources/keystore/keystore.p12
    key-store-password: ironclaw
    key-store-type: PKCS12
    enabled-protocols: TLSv1.3

opentracing:
  jaeger:
    log-spans: true
    service-name: mimock

spring:
  application:
    name: mimock

  main:
    banner-mode: off

  servlet:
    multipart:
      max-file-size: 10MB
      resolve-lazily: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  web:
    resources:
      static-locations: classpath:/static/mimock-ui/

  devtools:
    restart:
      enabled: true
      poll-interval: 1s
    livereload:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: mimock_schema_dev
        types:
          print:
            banner: false
        generate_statistics: true
        order_inserts: true
        order_updates: true

  datasource:
    url: jdbc:postgresql://localhost:5432/mimock_db
    username: mimock
    password: ironclaw
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: mimock_schema_dev
      auto-commit: false

  liquibase:
    change-log: classpath:/db/liquibase-changelog.xml
    default-schema: mimock_schema_dev
    liquibase-schema: mimock_schema_dev
    user: mimock
    password: ironclaw

app:
  security:
    jwt-expiry-duration: 10d
    jwt-secret-key: ${random.value} # Only for development. Do not use this in production.
    cors-config:
      allowed-origins: http://localhost:3000,http://localhost:3001
      allowed-methods: POST,GET,PUT,DELETE,OPTIONS
      allowed-headers: Authorization,Content-Type,X-Requested-With,Accept,X-XSRF-TOKEN
      exposed-headers: Cache-Control,Content-Language,Content-Length,Content-Type,Content-Disposition,Expires,Last-Modified,Pragma

springdoc:
  swagger-ui:
    doc-expansion: none
    csrf:
      enabled: true
      header-name: X-XSRF-TOKEN

flush-bin-cron-expression: "0 0 3 1 * *"

management:
  endpoints:
    web:
      base-path: "/api/mimock/monitoring"
      exposure:
        include:
          - health
          - info
          - prometheus
