export const constants = {
	headerTitle: 'Tools',
	title: {
		exportMocksBtn: 'Export Mocks',
		importMocksBtn: 'Coming Soon!!',
	},
	label: {
		exportImportComponent: 'Bulk Operations',
		exportMocksBtn: 'Export',
		importMocksBtn: 'Import',
		badgeFilter: 'Filter By HTTP Method',
		responseType: 'Filter By Response Type',
		sortSelect: 'Sort By',
	},
	name: {
		exportMocksBtn: 'exportMocks',
		importMocksBtn: 'importMocks',
		responseType: 'response-type',
	},
	ids: {
		exportMocksBtn: 'export-mocks-btn',
		importMocksBtn: 'import-mocks-btn',
		badgeFilter: 'badge-filter_',
		responseType: 'response_type_',
		sortSelect: 'sort-selector',
	},
	testIds: {
		sidebarContainer: 'sidebar-container',
		sidebarHeader: 'sidebar-header',
		exportImportComponent: 'bulk-operations',
		exportMocksBtn: 'export-mocks-btn',
		importMocksBtn: 'import-mocks-btn',
		badgeFilterComponent: 'badge-filters',
		badgeFilter: 'badge-filter_',
		responseTypeComponent: 'response-types',
		responseType: 'response_type_',
		sortSelectComponent: 'sort-selectors',
		sortSelect: 'sort-selector',
	},
	sortSelectItems: [
		{ label: 'Mock Name', value: 'mockName' },
		{ label: 'Http Method', value: 'httpMethod' },
		{ label: 'Status Code', value: 'statusCode' },
		{ label: 'Route', value: 'route' },
		{ label: 'Time Created', value: 'createdAt' },
		{ label: 'Last Modified', value: 'updatedAt' },
	],
	responseTypeItems: [
		{ label: 'Textual Response', value: 'TEXTUAL_RESPONSE' },
		{ label: 'Binary Response', value: 'BINARY_RESPONSE' },
		{ label: 'No Response', value: 'EMPTY_RESPONSE' },
	],
	badgeFilterItems: [
		{
			httpMethod: 'GET',
			badgeColor: 'border-blue-500 text-blue-500',
			activeBadgeColor: 'border-blue-400 bg-blue-500 text-white',
		},
		{
			httpMethod: 'POST',
			badgeColor: 'border-green-500 text-green-500',
			activeBadgeColor: 'border-green-400 bg-green-500 text-white',
		},
		{
			httpMethod: 'PUT',
			badgeColor: 'border-yellow-500 text-yellow-500',
			activeBadgeColor: 'border-yellow-400 bg-yellow-500 text-black',
		},
		{
			httpMethod: 'DELETE',
			badgeColor: 'border-red-500 text-red-500',
			activeBadgeColor: 'border-red-400 bg-red-500 text-white',
		},
		{
			httpMethod: 'PATCH',
			badgeColor: 'border-yellow-900 text-yellow-900',
			activeBadgeColor: 'border-yellow-800 bg-yellow-900 text-white',
		},
		{
			httpMethod: 'CONNECT',
			badgeColor: 'border-pink-500 text-pink-500',
			activeBadgeColor: 'border-pink-400 bg-pink-500 text-white',
		},
		{
			httpMethod: 'HEAD',
			badgeColor: 'border-indigo-500 text-indigo-500',
			activeBadgeColor: 'border-indigo-400 bg-indigo-500 text-white',
		},
		{
			httpMethod: 'TRACE',
			badgeColor: 'border-violet-500 text-violet-500',
			activeBadgeColor: 'border-violet-400 bg-violet-500 text-white',
		},
	],
};
