name: Mimock Backend Pipeline

on:
  push:
    paths:
      - 'mimock-backend/**'
      - '.github/workflows/*-backend.yml'
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Mimock Linter
    runs-on: ubuntu-latest
    env:
      MIMOCK_CURRENT_VERSION: ${{ secrets.MIMOCK_CURRENT_VERSION }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - uses: gradle/wrapper-validation-action@v1

      - name: Gradle Cache
        uses: burrunan/gradle-cache-action@v1

      - name: Check format using checkstyle
        working-directory: mimock-backend
        run: ./gradlew checkstyleMain

      - name: Publish style report
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-report
          path: |
            mimock-backend/build/reports/checkstyle/*

  test:
    needs:
      - lint
    name: Test Mimock
    runs-on: ubuntu-latest
    env:
      MIMOCK_CURRENT_VERSION: ${{ secrets.MIMOCK_CURRENT_VERSION }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Gradle Cache
        uses: burrunan/gradle-cache-action@v1

      - name: Run mimock tests in CI mode
        working-directory: mimock-backend
        run: ./gradlew clean startDatabase jacocoTestCoverageVerification -Drevision=$MIMOCK_CURRENT_VERSION -Dspring.config.location=classpath:/application.yml

      - name: Publish coverage report codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          commit_parent: ${{ github.sha }}

      - name: Publish coverage report
        uses: actions/upload-artifact@v3
        with:
          name: mimock-coverage-report
          path: |
            mimock-backend/build/reports/jacoco/test/html/*

  package-app:
    needs:
      - test
    name: Package Mimock
    runs-on: ubuntu-latest
    env:
      MIMOCK_CURRENT_VERSION: ${{ secrets.MIMOCK_CURRENT_VERSION }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Gradle Cache
        uses: burrunan/gradle-cache-action@v1

      - name: Build Mimock JAR
        working-directory: mimock-backend
        run: ./gradlew clean bootJar

      - name: Publish JAR
        uses: actions/upload-artifact@v3
        with:
          name: mimock-jar
          path: |
            mimock-backend/build/libs/*

      - name: Build mimock docker image
        run: |
          docker build -t mimock-backend:${{ github.sha }} . -f ./Dockerfile.slim --build-arg MIMOCK_CURRENT_VERSION=$MIMOCK_CURRENT_VERSION && echo "Docker image build validated"
          docker system prune && docker image prune --all
