name: Mimock E2E Pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  cypress-e2e-chrome:
    name: Running mimock e2e tests on chrome
    runs-on: ubuntu-latest
    env:
      MIMOCK_CURRENT_VERSION: ${{ secrets.MIMOCK_CURRENT_VERSION }}
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Start mimock
        run: SKIP_TESTS=true make start-app-container

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          working-directory: e2e
          record: true
          tag: node-${{ matrix.node-version }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
