name: Mimock E2E Pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  cypress-e2e-chrome:
    name: Running mimock e2e tests on chrome
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start mimock
        run: SKIP_TESTS=true make start-app-container

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          working-directory: e2e
          record: true
          tag: node-16
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
