name: Mimock E2E Pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  cypress-e2e:
    name: Running mimock e2e tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start mimock
        run: SKIP_TESTS=true make start-app-container

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: ${{ matrix.browser }}
          working-directory: e2e
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
